type: http_request
model: http_request
id: rq_MZPsNWBMhN
createdAt: 2025-08-03T16:33:26.402973
updatedAt: 2025-08-03T16:33:44.399879
workspaceId: wk_bBoraEVHnK
folderId: fl_JK7iKL4dYC
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers: []
method: GET
name: Sort by reputation
sortPriority: 10000.0
url: ${[ base_url ]}/v2/public/arkhamdb-decklists/search
urlParameters:
- enabled: true
  name: sort_by
  value: user_reputation
  id: 8Wr58k4ckg
- enabled: true
  name: ''
  value: ''
  id: BUhgHma7af
