type: folder
model: folder
id: fl_JK7iKL4dYC
createdAt: 2025-08-02T23:35:19.907711
updatedAt: 2025-08-03T14:57:23.140233
workspaceId: wk_bBoraEVHnK
folderId: null
authentication: {}
authenticationType: null
description: ''
headers: []
name: Decklists Search
sortPriority: 1000.0
