type: http_request
model: http_request
id: rq_DjhvvdGC2z
createdAt: 2025-08-03T15:00:23.698914
updatedAt: 2025-08-07T21:50:50.615666
workspaceId: wk_bBoraEVHnK
folderId: fl_JK7iKL4dYC
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers: []
method: GET
name: Required cards
sortPriority: 4000.0
url: ${[ base_url ]}/v2/public/arkhamdb-decklists/search
urlParameters:
- enabled: true
  name: with
  value: '08093'
  id: R8m37g00S6
- enabled: true
  name: ''
  value: ''
  id: ewZgJegWMd
